services:
  caddy:
    build: .
    image: caddy-naive:latest
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv/site:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
